988 - Gnosis safe
PrimeDAO/prime-deals-dapp pull request #1013
Opened 2022-05-17 19:30 UTC by hiaux0

## What was done
- add gnosis safe package
`npm i @gnosis.pm/safe-apps-web3modal @gnosis.pm/safe-apps-sdk`
- add `manifest.json`
  Needed as described here:
  - https://docs.gnosis-safe.io/build-with-safe/sdks/safe-apps/get-started#manifest
  - More info here
    - https://docs.gnosis-safe.io/build-with-safe/sdks/safe-apps/releasing-your-safe-app#get-your-safe-app-listed-in-the-safe
- add CORS to `vercel.json`
  - needed: https://docs.gnosis-safe.io/build-with-safe/sdks/safe-apps/get-started#cors
  - vercel docs: https://vercel.com/support/articles/how-to-enable-cors#enabling-cors-using-vercel.json

## Testing
- Make sure wallet is behaving the same
```
- [x] connecting
  - [x] manually (connect)
  - [x] pops ups metamask
- [x] or automatically (wallet cached)
- [x] disconnecting has to work
- [x] Change account within metamask
```

#### Before
Wallet works

#### After
Wallet works
Appears in Gnosis Safe App

2022-05-17 23:23 UTC, hiaux0 commented
## Findings
#### Adding Custom App to Gnosis safe
- following docs https://help.gnosis-safe.io/en/articles/4022030-add-a-custom-safe-app
- manifest.json exists (on prod, this does not exists, neither is the Custom App recognized in Gnosis. This tells me, this branch is somehow working)
  - https://prime-deals-dapp-git-feat-988-gnosis-safe-curvelabs.vercel.app/manifest.json
![image](https://user-images.githubusercontent.com/30693990/168927850-18360479-cadd-4a0d-a5e9-269564964163.png)

2022-06-02 17:59 UTC, dkent600 requested changes

2022-06-02 17:59 UTC, dkent600 commented on firebaseFunctions/src/hash-validation.ts
> +const ProviderEndpoints = {
Bummer to duplicate this from ethereumservice

2022-06-02 17:59 UTC, dkent600 commented on firebaseFunctions/src/hash-validation.ts
> +const NEW_PROXY_VERSION = "1.3.0";
Why do you call this "proxy"?  Is it really?  Or is this better called something like "NEW_SAFE_CONTRACT_VERSION"

2022-06-02 17:59 UTC, dkent600 commented on firebaseFunctions/src/index.ts
> +         * 2. The WalletConnect Safe App uses EIP-1271
Why do you say "WalletConnect"?  This is certainly needed when running as a Safe App, but that has nothing to do with WalletConnect.  Is it also needed when using a Safe Wallet from WalletConnect?  What about other wallets?

2022-06-02 17:59 UTC, dkent600 commented on index.ejs
> +  <link rel="manifest" href="manifest.json"/>
should this be in a separate PR?  No big deal, but if this is required by Safe, maybe we can document it here.

2022-06-09 09:38 UTC, merged