Add Primary DAO stage e2e
PrimeDAO/prime-deals-dapp pull request #134
Opened 2022-02-09 12:17 UTC by paweljanicki

## What was done

## Testing

#### Before

#### After

2022-02-09 14:43 UTC, hiaux0 reviewed
Overall looks good!
I just had a high level view, but no bigger issue to comment on.

The only thing I see, is that we can split the .feature files now.
Eg. "Creating an open Deal" is one specific Feature, but it has so many "Scenarios" to it, that
we can create more .feature files, and treat it like "Sub features".
What I can think of right now is
```
/features/deals/openDeal/stages
/features/deals/openDeal/stages/primaryDAOStages
/features/deals/openDeal/stages/primaryDAOStages/representatives.feature
/features/deals/openDeal/stages/primaryDAOStages/avatar.feature
```

Something along that line.
Dunno if this exact split makes sense, but at least trying to reduce the number of Scenarios per Feature is desirable.

2022-02-18 10:34 UTC, hiaux0 commented on src/services/utils.ts
> +  // @TODO discuss using library like lodash or underscore
I'd say let's use tools, that make us develop faster.
After that worry about bundling and performance.

So +1 for lodash (over underscore)

2022-02-18 10:40 UTC, paweljanicki commented on cypress/integration/tests/deals/shared/dao-stage.ts
> +      expect($representatives).to.have.length(1);
Okk

2022-02-18 10:41 UTC, paweljanicki commented on cypress/integration/tests/deals/make-an-offer-wizard.e2e.ts
> +})
Let's leave it here for now, but it will have to be updated once we stop using the mock data

2022-02-18 10:42 UTC, paweljanicki commented on cypress/integration/tests/deals/shared/dao-stage.ts
> +import { Then, When } from "@badeball/cypress-cucumber-preprocessor/methods";
I wasn't sure where to put it. I will move it

2022-02-18 10:44 UTC, paweljanicki commented on src/services/ImageService.ts
> +      }
For sure, I think this could be a custom Error, like `throw new CorsError()` and yes I will comment what is it for

2022-02-18 12:55 UTC, hiaux0 commented on src/services/ValidationService.ts
> +  "Please enter valid image URL",
```suggestion
  "URL is not an image",
```
Reason: what's "valid"?

2022-02-19 16:25 UTC, dkent600 requested changes
When I create duplicate address, then delete all but one of the dups, it still has the error message:

![image](https://user-images.githubusercontent.com/1821666/154809095-92c202e5-fc3a-4f40-8327-c9424e637a4f.png)

2022-02-19 16:25 UTC, dkent600 commented on src/entities/DealRegistrationTokenSwap.ts
> +  logo_url: string;
would be consistent with tokens to call this "logoURI"

2022-02-19 16:25 UTC, dkent600 commented on src/services/ImageService.ts
> +      const xhr = new XMLHttpRequest();
Would be best if we can use axios, thanks

2022-02-19 16:25 UTC, dkent600 commented on src/services/ImageService.ts
> +        throw new Error();
Agreed, we need to have messages associated with all errors.

2022-02-19 16:25 UTC, dkent600 commented on src/services/ValidationService.ts
> +  "Please enter valid image URL",
"The URL does not point to an image"

2022-02-21 15:46 UTC, dkent600 approved these changes

2022-02-21 15:50 UTC, merged