increased lead details stage address input width
PrimeDAO/prime-deals-dapp pull request #282
Opened 2022-03-07 18:59 UTC by IonelLupu

2022-03-07 23:09 UTC, dkent600 requested changes
Should be "Make me the proposal lead", not "Make me admin"

And I really don't like "CONNECT WALLET".  It is butt ugly, and gives no reason why one should connect.  Look at Launch:

![image](https://user-images.githubusercontent.com/1821666/157133459-02fe17b2-a7cf-4a8d-a380-1a12bdff292a.png)

2022-03-08 17:58 UTC, IonelLupu commented
Based on the chat discussion, I will implement this:
![image](https://user-images.githubusercontent.com/4083652/157297688-5fdf80e4-3cd8-4250-af2a-ecc684a30a17.png)

2022-03-08 22:05 UTC, dkent600 requested changes

2022-03-08 22:05 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/stages/leadDetailsStage/leadDetailsStage.html
> +          Make me admin
Should be "Make Me the Proposal Lead"

2022-03-09 11:37 UTC, dkent600 approved these changes

2022-03-09 11:37 UTC, merged