Fix/wizard delete button for 1
PrimeDAO/prime-deals-dapp pull request #328
Opened 2022-03-11 12:25 UTC by hiaux0

## What was done

## Testing

#### Before

#### After
- clause
![image](https://user-images.githubusercontent.com/30693990/157866524-9ad9b0f6-8eb9-4706-b917-3c064954c991.png)

- tokenDetail
![image](https://user-images.githubusercontent.com/30693990/157866487-6e117d20-a77e-4fa0-bdcb-62c1e85b2b49.png)

2022-03-12 15:38 UTC, dkent600 requested changes

2022-03-12 15:38 UTC, dkent600 commented on src/resources/elements/editingCard/editingCard.ts
> +  @bindable.boolean hideDeleteButton: boolean;
Can we explicitly set the default to false?

2022-03-14 22:13 UTC, dkent600 approved these changes

2022-03-15 10:34 UTC, hiaux0 commented
Conflicts resovled

2022-03-15 14:46 UTC, merged