Introducing `pselect`
PrimeDAO/prime-deals-dapp pull request #34
Opened 2022-01-01 15:33 UTC by giladt

# `pselect`- dropdown

Options Data:
```
{
  value: string,
  text: string,
  innerHTML: string
}
```

Optional Parameters: 
`is-searchable` - enables search box in dropdown. Default: false
`placeholder` - placeholder text for initial state. Default: 'Please Select...'

![select-dropdown](https://user-images.githubusercontent.com/2517870/147853952-56cb54e9-3537-4d16-90fe-7687103acbea.gif)

2022-01-03 23:09 UTC, dkent600 requested changes
1) should remove the yarn.lock file.  We're aligned around npm.
2) Where ever possible, would prefer if we can have less HTML in the typescript.

2022-01-03 23:09 UTC, dkent600 commented on src/resources/elements/primeDesignSystem/pselect/pselect.ts
> + *    <pselect type="primary">Primary</pselect>
need to update this documentation

2022-01-03 23:09 UTC, dkent600 commented on src/resources/elements/primeDesignSystem/pselect/pselect.ts
> +  @bindable data: Array<{value: string, text: string, innerHTML: string}>;
Should export this as an interface like IpSelectItemConfig so consumer can get intellisense/compile errors.

2022-01-03 23:09 UTC, dkent600 commented on src/resources/elements/primeDesignSystem/pselect/pselect.ts
> +      placeholder: "<span class=\"loading\"><i class=\"fas fa-circle-notch\" ></i> Loading...</span>",
ouch more html in the typescript

2022-01-03 23:09 UTC, dkent600 commented on src/resources/elements/primeDesignSystem/pselect/pselect.ts
> +      searchText: "DAO Name is missing.",
This control shouldn't know anything about DAOs.  Should be agnostic.

2022-01-03 23:09 UTC, dkent600 commented on src/services/DealService.ts
> +        ? (dao.logo.includes("http"))
you mean startsWith?  case insensitive?

2022-01-05 21:56 UTC, giladt commented on src/registry-wizard/baseStage.scss
> +          select,
Actually, I'm not sure it's needed at all. It's part of the initial commit (means, I've copied it from launch). I won't touch it here. That can be part of the refactor of the reg wizard, IMO.

2022-01-06 20:12 UTC, dkent600 approved these changes

2022-01-07 11:36 UTC, giladt commented
Moved To a new PR

2022-01-07 11:36 UTC, closed without merging