479 - Authorized any connected user to comment open deal
PrimeDAO/prime-deals-dapp pull request #495
Opened 2022-03-29 18:15 UTC by giladt

## What was done
Allowed any connected wallet to begin a discussion and/or comment on a thread.

2022-03-31 08:49 UTC, hiaux0 reviewed
.

2022-03-31 08:49 UTC, hiaux0 commented on src/dealDashboard/dealDashboard.ts
> +          ...this.deal.registrationData.partnerDAO?.representatives.map(representative => representative.address) || "",
For the future: 
Could maybe reuse methods from current PR from @IonelLupu 
https://github.com/PrimeDAO/prime-deals-dapp/pull/499/files#diff-73772712224a2110ee6dd67f201fb8721e0ea04e41a2f67bc214cc7ac088d059=

2022-03-31 19:20 UTC, dkent600 requested changes

2022-03-31 20:47 UTC, dkent600 requested changes

2022-03-31 20:47 UTC, dkent600 commented on src/dealDashboard/dealDashboard.ts
> +        [...this.deal.representativesAndLead].includes(this.ethereumService.defaultAccountAddress)
First, note the correct say to use Set.  But you don't need this anyway, use `deal.isRepresentativeUser` (which does it corrrectly)

2022-04-02 12:36 UTC, giladt commented on src/dealDashboard/dealDashboard.ts
> +  get authorized(): boolean {
this getter is actually not needed anymore, as it is not used anywhere- replaced in the view with deal properties.

2022-04-02 12:43 UTC, hiaux0 reviewed
ez fix

2022-04-02 23:04 UTC, dkent600 approved these changes

2022-04-02 23:04 UTC, merged