Add firebase observability to the playground
PrimeDAO/prime-deals-dapp pull request #503
Opened 2022-03-30 08:47 UTC by paweljanicki

## What was done

## Testing

#### Before

#### After

2022-03-30 13:56 UTC, paweljanicki commented on src/services/FirestoreService.ts
> +  }> {
This is a method where we listen to what was added, modified and removed @dkent600

2022-03-31 20:24 UTC, dkent600 commented
Ooops, sorry, didn't notice this was just a draft.  So I won't merge.

2022-03-31 20:32 UTC, dkent600 approved these changes

2022-03-31 20:44 UTC, dkent600 requested changes
To the extend this is about introducing rxjs, then I wouldn't want to merge it.

2022-04-19 13:20 UTC, paweljanicki commented
Not intended to be merged

2022-04-19 13:20 UTC, closed without merging