Feature/web socket for like and delete
PrimeDAO/prime-deals-dapp pull request #576
Opened 2022-04-05 14:42 UTC by giladt

## What was done
The comment thread is updated by WebSocket events for like and delete (in addition to new comment)

2022-04-05 21:16 UTC, dkent600 requested changes

2022-04-05 21:16 UTC, dkent600 commented on src/dealDashboard/dealDiscussion/discussionThread/discussionThread.ts
> +  private streamIDs = new Set;
should be new Set(), no?

2022-04-06 09:42 UTC, hiaux0 commented on src/dealDashboard/dealDiscussion/discussionThread/discussionThread.ts
>    private async updateCommentsThreadUponMessageArrival(comment: Types.Message): Promise<void> {
Nit: 
```suggestion
  private async updateCommentsThreadUponMessageArrival(commentStreamMessage: Types.Message): Promise<void> {
```

I was confused, and expected the type `IComment` based on naming of param `comment`

2022-04-06 09:42 UTC, hiaux0 commented on src/dealDashboard/dealDiscussion/discussionThread/discussionThread.ts
> +    const newComment: IComment = {...comment.data};
What's the goal of the spread?

If want a deepCopy, then we might want to add `Utils.cloneDeep() {  json.parse(json.stringify)  }`

2022-04-06 11:55 UTC, dkent600 approved these changes

2022-04-06 11:55 UTC, merged