feat(wizard): update various text copies
PrimeDAO/prime-deals-dapp pull request #619
Opened 2022-04-08 11:40 UTC by hiaux0

## What was done

## Testing

#### Before

#### After

##### Proposal
![image](https://user-images.githubusercontent.com/30693990/162424873-b12657d0-9092-4f65-be28-609a0ccd8ccc.png)

##### Lead Details
![image](https://user-images.githubusercontent.com/30693990/162428485-e7725981-6937-49db-9d4b-7e1fa930570f.png)

##### Primary/Partner DAO
![image](https://user-images.githubusercontent.com/30693990/162428547-7e798b51-e178-4046-ba53-4dd796d04ec4.png)

##### Token Details
![image](https://user-images.githubusercontent.com/30693990/162428616-02c53311-f917-4c85-aa8a-9dba1afc8813.png)

2022-04-08 18:50 UTC, dkent600 requested changes

2022-04-08 18:50 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/components/tokenDetails/tokenDetails.html
> +        label-description="Once the deal is executed on-chain, the Instant Transfer amount will be immediately sent to the other DAO’s treasury address, whereas the Vested amount will define the amou
"Set-up" should be "setup"

2022-04-08 18:51 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/stages/partnerDaoStage/partnerDaoStage.html
> +        Note, that the Proposal Lead is not allowed to deposit funds from the UI, nor to partake in the voting process unless their address is also listed as Representative, so if you want to also fu
should be just one '.'

2022-04-08 18:52 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/stages/primaryDaoStage/primaryDaoStage.html
> +        Note, that the Proposal Lead is not allowed to deposit funds from the UI, nor to partake in the voting process unless their address is also listed as Representative, so if you want to also fu
"Note, that" should be "Note that"

Should be only one '.'

2022-04-08 18:53 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/stages/proposalStage/proposalStage.html
> +          This wizard will guide you through the process. You can always come back to edit your input before you hit the <strong>submit</strong> button at the end of the wizard.
"hit the <strong>submit</strong>" should be "click the <strong>SUBMIT</strong>"

2022-04-11 13:54 UTC, hiaux0 reviewed
.

2022-04-11 16:28 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/components/tokenDetails/tokenDetails.html
> +        label="Instant Transfer Setup"
yes, thanks

2022-04-11 16:28 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/components/tokenDetails/tokenDetails.html
> +      <pform-input label="Vesting Setup"
yes

2022-04-11 22:08 UTC, hiaux0 commented on src/wizards/tokenSwapDealWizard/components/tokenDetails/tokenDetails.html
> +        label="Instant Transfer Setup"
Sry meant to express that I did the change already, and asked whether you were okay with them.

2022-04-11 22:08 UTC, hiaux0 commented on src/wizards/tokenSwapDealWizard/components/tokenDetails/tokenDetails.html
> +      <pform-input label="Vesting Setup"
Sry meant to express that I did the change already, and asked whether you were okay with them.

2022-04-12 01:47 UTC, dkent600 approved these changes

2022-04-12 01:47 UTC, merged