renamed social links to external links
PrimeDAO/prime-deals-dapp pull request #682
Opened 2022-04-16 16:44 UTC by IonelLupu

added additional external links

## What was done

## Testing

#### Before

#### After

2022-04-16 19:03 UTC, hiaux0 requested changes
Need submit page as well.

Else looks good (dropdown updated too :+1: )
![image](https://user-images.githubusercontent.com/30693990/163688093-580f06de-35b9-4c94-bab4-a7d9a45cbb4d.png)

2022-04-17 03:20 UTC, dkent600 requested changes

2022-04-17 03:20 UTC, dkent600 commented on src/wizards/tokenSwapDealWizard/dealWizardTypes.ts
> +    name: "Youtube",
Should be "YouTube"

2022-04-17 12:45 UTC, dkent600 approved these changes

2022-04-17 14:07 UTC, merged