Update firebase authentication message
PrimeDAO/prime-deals-dapp pull request #806
Opened 2022-04-27 07:30 UTC by paweljanicki

## What was done
- Update authentication message
- Don't request part of the message to sign from firebase function - create message to sign (aka authentication message) entirely on the frontend
- Send message, alongside address and signature to firebase function `verifySignedMessageAndCreateCustomToken`

## Testing
- connect, disconnect, switch accounts

#### Before
- signature could be used only once

#### After
- signature can be reused

2022-04-27 12:16 UTC, dkent600 requested changes
don't show metamask message unless needed

2022-04-28 11:08 UTC, hiaux0 reviewed
## Behavior
### Local storage
> Store user signatures in local storage

1. Could you add more explanation around what the code is doing?
2. Do we only check if signature present in localStorage without another verification to firebase?
3. How do sessions work now? (ie. how long is a signature valid?)

Overall I'd like to have more documentation around the changes

### Disconnect
When I disconnect from Metamask, then reconnect, I don't get a firebase signature request.
But I should?

2022-04-28 11:08 UTC, hiaux0 commented on src/app.ts
> +      this.modalMessage = "Thank you for your patience while we initialize for a few moments...";
Same text string is used in multiple places -> should add a constant imo.
(Future: think this message is also used in other files, so we should add a concept of "text copies" as a file or directory)

2022-04-28 12:41 UTC, dkent600 approved these changes

2022-04-28 12:42 UTC, merged