feat(discussions.comment): loading indicator when replying
PrimeDAO/prime-deals-dapp pull request #852
Opened 2022-04-28 13:44 UTC by hiaux0

## What was done
- add loading indicator
  - note, it will indicate loading for _all_ comments. 
  - Imo a nice feature from network perspective to block further requests
  - though might be annoying for user if loading times are long
    - imo good balance, as we are not super confident around theconvo network yet
- and disable the reply button

## Testing
reply to a comment

#### Before
no loading indicator

#### After
![image](https://user-images.githubusercontent.com/30693990/165765812-d7e2aaf0-cf80-4fd5-a8e5-ef105039f6f4.png)

2022-04-29 09:24 UTC, giladt requested changes

2022-04-29 09:24 UTC, giladt commented on src/dealDashboard/dealDiscussion/discussionThread/discussionThread.html
> +          is-loading.bind="true"
Why is it here?
Maybe something like:
`is-loading.bind="isLoading.commenting || isLoading.replying"`?

2022-04-30 08:50 UTC, giladt requested changes
![reply](https://user-images.githubusercontent.com/2517870/166098507-62602f15-8615-44ac-99e3-b611f8710f25.gif)

Two points to consider:
- When we press cancel- it fetches the comment again. Probably best to skip it.
- While moving the cursor away from the comment, there's no indication of loading. Not sure where will it be the best to indicate it though, op.1 next to the like icon, op2. next to the "comment" title at the bottom?

2022-05-02 09:48 UTC, hiaux0 commented
> Two points to consider:
    When we press cancel- it fetches the comment again. Probably best to skip it.
    While moving the cursor away from the comment, there's no indication of loading. Not sure where will it be the best to indicate it though, op.1 next to the like icon, op2. next to the "comment" title at the bottom?

Good points, I'll create a ticket for that.

Would like to keep this PR to what was requested:
> decision: yes to disabling the button and to providing a spinny icon (in the button)

2022-05-02 14:48 UTC, merged